version: '3.8'

services:
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - 80:80
      - 8081:443
    volumes:
      - ./proxy/srv/:/srv/
    depends_on:
      - alert
  
  alert:
    build: ./alert
    container_name: alert
    ports:
      - 5000:5000
    

networks: 
  default: 
    external: 
      name: capstone-dev-network