# Generated by Django 3.2.10 on 2022-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamingSessions', '0002_activeprojects_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
